# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-07 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20151207_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.CharField(default='itempic_filename', max_length=255, verbose_name='\u041f\u0443\u0442\u044c \u043a \u043a\u0430\u0440\u0442\u0438\u043d\u043a\u0435 \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.CharField(default='categpic_filename', max_length=255, verbose_name='\u041f\u0443\u0442\u044c \u043a \u043a\u0430\u0440\u0442\u0438\u043d\u043a\u0435 \u0442\u043e\u0432\u0430\u0440\u0430'),
        ),
    ]
