# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-07 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20151207_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.CharField(default='category_image_filename', max_length=255, verbose_name='\u0418\u043c\u044f \u043a\u0430\u0440\u0442\u0438\u043d\u043a\u0438 \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.CharField(default='item_image_filename', max_length=255, verbose_name='\u0418\u043c\u044f \u043a\u0430\u0440\u0442\u0438\u043d\u043a\u0438 \u0442\u043e\u0432\u0430\u0440\u0430'),
        ),
    ]
