# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-07 19:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20151207_1932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='image_cat',
            new_name='image',
        ),
    ]
