# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20151207_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='available',
            field=models.CharField(choices=[('shop', '\u0412 \u043d\u0430\u043b\u0438\u0447\u0438\u0438'), ('stock', '\u041f\u043e \u043f\u0440\u0435\u0434\u0437\u0430\u043a\u0430\u0437\u0443')], default='shop', max_length=5),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.CharField(default='category_image_filename', max_length=255, verbose_name='\u041f\u0443\u0442\u044c \u043a \u043a\u0430\u0440\u0442\u0438\u043d\u043a\u0435 \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.CharField(default='item_image_filename', max_length=255, verbose_name='\u041f\u0443\u0442\u044c \u043a \u043a\u0430\u0440\u0442\u0438\u043d\u043a\u0435 \u0442\u043e\u0432\u0430\u0440\u0430'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0442\u043e\u0432\u0430\u0440\u0430'),
        ),
    ]
