# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 12:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20151209_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='available',
        ),
    ]
