# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_item_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='available',
            field=models.CharField(choices=[('available', '\u0412 \u043d\u0430\u043b\u0438\u0447\u0438\u0438'), ('pre-order', '\u041f\u043e \u043f\u0440\u0435\u0434\u0437\u0430\u043a\u0430\u0437\u0443')], default='available', max_length=9),
        ),
    ]
